[package]
name = "tarfs-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
env_logger = "0.9.0"
fuser = "0.9.1"
libc = "0.2.112"
log = "0.4.14"
tar = "0.4.38"
